/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home;

import Log_IN.govt_login;

/**
 *
 * @author AL-SABA
 */
public class govt_home extends javax.swing.JFrame {

    /**
     * Creates new form govt_home
     */
    public govt_home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        bg02 = new javax.swing.JLabel();
        home_button_01 = new javax.swing.JLabel();
        registation_button_01 = new javax.swing.JLabel();
        bordresult_button_01 = new javax.swing.JLabel();
        notic_button_01 = new javax.swing.JLabel();
        logout_button_01 = new javax.swing.JLabel();
        govt_panel_01 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        bg01 = new javax.swing.JLabel();
        home_button_02 = new javax.swing.JLabel();
        registation_button_02 = new javax.swing.JLabel();
        bordresult_button_02 = new javax.swing.JLabel();
        notic_button_02 = new javax.swing.JLabel();
        logout_button_02 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/govt bg.png"))); // NOI18N
        bg02.setToolTipText("");
        jPanel6.add(bg02, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, -1, 70));

        home_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Home button 01.png"))); // NOI18N
        home_button_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home_button_01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home_button_01MouseExited(evt);
            }
        });
        jPanel6.add(home_button_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 147, -1, -1));

        registation_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/registation button 01.png"))); // NOI18N
        registation_button_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registation_button_01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registation_button_01MouseExited(evt);
            }
        });
        jPanel6.add(registation_button_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 234, -1, -1));

        bordresult_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Board result button 01.png"))); // NOI18N
        bordresult_button_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                bordresult_button_01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                bordresult_button_01MouseExited(evt);
            }
        });
        jPanel6.add(bordresult_button_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 325, -1, -1));

        notic_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Notice button 01.png"))); // NOI18N
        notic_button_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                notic_button_01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                notic_button_01MouseExited(evt);
            }
        });
        jPanel6.add(notic_button_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));

        logout_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Log out button 01.png"))); // NOI18N
        logout_button_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_button_01MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout_button_01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout_button_01MouseExited(evt);
            }
        });
        jPanel6.add(logout_button_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        govt_panel_01.addTab("tab1", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        govt_panel_01.addTab("tab2", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 615, Short.MAX_VALUE)
        );

        govt_panel_01.addTab("tab3", jPanel3);

        jPanel5.setBackground(new java.awt.Color(232, 230, 217));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 830, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 609, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        govt_panel_01.addTab("tab4", jPanel4);

        jPanel6.add(govt_panel_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, -10, 830, 650));

        bg01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/govt home.png"))); // NOI18N
        jPanel6.add(bg01, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, -1, -1));

        home_button_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Home button 02.png"))); // NOI18N
        jPanel6.add(home_button_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        registation_button_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/registation button 02.png"))); // NOI18N
        jPanel6.add(registation_button_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 230, 40));

        bordresult_button_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Board result button 02.png"))); // NOI18N
        jPanel6.add(bordresult_button_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 337, -1, 30));

        notic_button_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Notice button 02.png"))); // NOI18N
        jPanel6.add(notic_button_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        logout_button_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Log out button 02.png"))); // NOI18N
        jPanel6.add(logout_button_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 460, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_button_01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_button_01MouseEntered
        home_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Home button 02.png")));
    }//GEN-LAST:event_home_button_01MouseEntered

    private void home_button_01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_button_01MouseExited
         home_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Home button 01.png")));
    }//GEN-LAST:event_home_button_01MouseExited

    private void registation_button_01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registation_button_01MouseEntered
        registation_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/registation button 02.png")));
    }//GEN-LAST:event_registation_button_01MouseEntered

    private void registation_button_01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registation_button_01MouseExited
        registation_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/registation button 01.png")));
    }//GEN-LAST:event_registation_button_01MouseExited

    private void bordresult_button_01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bordresult_button_01MouseEntered
        bordresult_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Board result button 02.png")));
    }//GEN-LAST:event_bordresult_button_01MouseEntered

    private void bordresult_button_01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bordresult_button_01MouseExited
        bordresult_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Board result button 01.png")));
    }//GEN-LAST:event_bordresult_button_01MouseExited

    private void notic_button_01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notic_button_01MouseEntered
       notic_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Notice button 02.png")));
    }//GEN-LAST:event_notic_button_01MouseEntered

    private void notic_button_01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notic_button_01MouseExited
       notic_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Notice button 01.png")));
    }//GEN-LAST:event_notic_button_01MouseExited

    private void logout_button_01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_button_01MouseEntered
       logout_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Log out button 02.png")));
    }//GEN-LAST:event_logout_button_01MouseEntered

    private void logout_button_01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_button_01MouseExited
        logout_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Log out button 01.png")));
    }//GEN-LAST:event_logout_button_01MouseExited

    private void logout_button_01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_button_01MouseClicked
        new govt_login().setVisible(true);
        dispose();
    }//GEN-LAST:event_logout_button_01MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(govt_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(govt_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(govt_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(govt_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new govt_home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bg01;
    private javax.swing.JLabel bg02;
    private javax.swing.JLabel bordresult_button_01;
    private javax.swing.JLabel bordresult_button_02;
    private javax.swing.JTabbedPane govt_panel_01;
    private javax.swing.JLabel home_button_01;
    private javax.swing.JLabel home_button_02;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JLabel logout_button_01;
    private javax.swing.JLabel logout_button_02;
    private javax.swing.JLabel notic_button_01;
    private javax.swing.JLabel notic_button_02;
    private javax.swing.JLabel registation_button_01;
    private javax.swing.JLabel registation_button_02;
    // End of variables declaration//GEN-END:variables
}
