/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home;

import Log_IN.student_login;

/**
 *
 * @author AL-SABA
 */
public class student_home extends javax.swing.JFrame {

    /**
     * Creates new form student_home
     */
    public student_home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        home_button_01 = new javax.swing.JLabel();
        result_button_01 = new javax.swing.JLabel();
        Boardresult_01 = new javax.swing.JLabel();
        certificate_01 = new javax.swing.JLabel();
        routine_01 = new javax.swing.JLabel();
        logout_01 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        home_button_02 = new javax.swing.JLabel();
        result_button_02 = new javax.swing.JLabel();
        Boardresult_02 = new javax.swing.JLabel();
        certificate_02 = new javax.swing.JLabel();
        routine_02 = new javax.swing.JLabel();
        logout_02 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/st bg.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 80));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        home_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Home button 03.png"))); // NOI18N
        home_button_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home_button_01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home_button_01MouseExited(evt);
            }
        });
        jPanel3.add(home_button_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 30, -1, -1));

        result_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Result button 01.png"))); // NOI18N
        result_button_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                result_button_01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                result_button_01MouseExited(evt);
            }
        });
        jPanel3.add(result_button_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));

        Boardresult_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Board Result 03.png"))); // NOI18N
        Boardresult_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                Boardresult_01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                Boardresult_01MouseExited(evt);
            }
        });
        jPanel3.add(Boardresult_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 270, -1));

        certificate_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Certificate 01.png"))); // NOI18N
        certificate_01.setToolTipText("");
        certificate_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                certificate_01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                certificate_01MouseExited(evt);
            }
        });
        jPanel3.add(certificate_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        routine_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Routine 01.png"))); // NOI18N
        routine_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                routine_01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                routine_01MouseExited(evt);
            }
        });
        jPanel3.add(routine_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, -1));

        logout_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Log Out button 03.png"))); // NOI18N
        logout_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_01MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout_01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout_01MouseExited(evt);
            }
        });
        jPanel3.add(logout_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 450, -1, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/st bg01.png"))); // NOI18N
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, -1));

        jTabbedPane1.addTab("tab1", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", jPanel7);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 585, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab5", jPanel8);

        jPanel3.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, -40, 750, 620));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/studennt home.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        home_button_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Home button 04.png"))); // NOI18N
        jPanel3.add(home_button_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, 110, 40));

        result_button_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Result button 02.png"))); // NOI18N
        jPanel3.add(result_button_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        Boardresult_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Board Result 04.png"))); // NOI18N
        jPanel3.add(Boardresult_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 270, 40));

        certificate_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Certificate 02.png"))); // NOI18N
        jPanel3.add(certificate_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, -1, -1));

        routine_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Routine 02.png"))); // NOI18N
        routine_02.setToolTipText("");
        jPanel3.add(routine_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        logout_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Log Out button 04.png"))); // NOI18N
        jPanel3.add(logout_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 420, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1200, 720));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_button_01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_button_01MouseEntered
        home_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Home button 04.png")));
    }//GEN-LAST:event_home_button_01MouseEntered

    private void home_button_01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_button_01MouseExited
        home_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Home button 03.png")));
    }//GEN-LAST:event_home_button_01MouseExited

    private void result_button_01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_result_button_01MouseEntered
        result_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Result button 02.png")));
    }//GEN-LAST:event_result_button_01MouseEntered

    private void result_button_01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_result_button_01MouseExited
       result_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Result button 01.png")));
    }//GEN-LAST:event_result_button_01MouseExited

    private void Boardresult_01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boardresult_01MouseEntered
        Boardresult_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Board Result 04.png")));
    }//GEN-LAST:event_Boardresult_01MouseEntered

    private void Boardresult_01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boardresult_01MouseExited
        Boardresult_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Board Result 03.png")));
    }//GEN-LAST:event_Boardresult_01MouseExited

    private void certificate_01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_certificate_01MouseEntered
         certificate_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Certificate 02.png")));
    }//GEN-LAST:event_certificate_01MouseEntered

    private void certificate_01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_certificate_01MouseExited
        certificate_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Certificate 01.png")));
    }//GEN-LAST:event_certificate_01MouseExited

    private void routine_01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_routine_01MouseEntered
        routine_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Routine 02.png")));
    }//GEN-LAST:event_routine_01MouseEntered

    private void routine_01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_routine_01MouseExited
        routine_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Routine 01.png")));
    }//GEN-LAST:event_routine_01MouseExited

    private void logout_01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_01MouseEntered
        logout_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Log Out button 04.png")));
    }//GEN-LAST:event_logout_01MouseEntered

    private void logout_01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_01MouseExited
        logout_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Log Out button 03.png")));
    }//GEN-LAST:event_logout_01MouseExited

    private void logout_01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_01MouseClicked
        new student_login().setVisible(true);
        dispose();
    }//GEN-LAST:event_logout_01MouseClicked

    /* /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(student_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(student_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(student_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(student_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new student_home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Boardresult_01;
    private javax.swing.JLabel Boardresult_02;
    private javax.swing.JLabel certificate_01;
    private javax.swing.JLabel certificate_02;
    private javax.swing.JLabel home_button_01;
    private javax.swing.JLabel home_button_02;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel logout_01;
    private javax.swing.JLabel logout_02;
    private javax.swing.JLabel result_button_01;
    private javax.swing.JLabel result_button_02;
    private javax.swing.JLabel routine_01;
    private javax.swing.JLabel routine_02;
    // End of variables declaration//GEN-END:variables
}
