/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package home;

import Log_IN.teacher_login;

/**
 *
 * @author AL-SABA
 */
public class teacher_home extends javax.swing.JFrame {

    /**
     * Creates new form teacher_home
     */
    public teacher_home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        home_button_01 = new javax.swing.JLabel();
        schoolresult_01 = new javax.swing.JLabel();
        registation_01 = new javax.swing.JLabel();
        admission_01 = new javax.swing.JLabel();
        routine_01 = new javax.swing.JLabel();
        logout_01 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();
        home_button_02 = new javax.swing.JLabel();
        schoolresult_02 = new javax.swing.JLabel();
        registation_02 = new javax.swing.JLabel();
        admission_02 = new javax.swing.JLabel();
        routine_02 = new javax.swing.JLabel();
        logout_02 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/tc bg.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 80));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 80));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/tc bg01.png"))); // NOI18N
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jTabbedPane1.addTab("tab1", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab2", jPanel4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab3", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab4", jPanel6);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 575, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("tab5", jPanel7);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 750, 610));

        home_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Home button 05.png"))); // NOI18N
        home_button_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                home_button_01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                home_button_01MouseExited(evt);
            }
        });
        getContentPane().add(home_button_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        schoolresult_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/school result 01.png"))); // NOI18N
        schoolresult_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                schoolresult_01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                schoolresult_01MouseExited(evt);
            }
        });
        getContentPane().add(schoolresult_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        registation_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/registation button 03.png"))); // NOI18N
        registation_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                registation_01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                registation_01MouseExited(evt);
            }
        });
        getContentPane().add(registation_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        admission_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/admission 01.png"))); // NOI18N
        admission_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                admission_01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                admission_01MouseExited(evt);
            }
        });
        getContentPane().add(admission_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, -1, -1));

        routine_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Routine 03.png"))); // NOI18N
        routine_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                routine_01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                routine_01MouseExited(evt);
            }
        });
        getContentPane().add(routine_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, -1, -1));

        logout_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Log Out button 05.png"))); // NOI18N
        logout_01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logout_01MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logout_01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logout_01MouseExited(evt);
            }
        });
        getContentPane().add(logout_01, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 510, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/teacher home.png"))); // NOI18N
        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, -1, 710));

        home_button_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Home button 06.png"))); // NOI18N
        getContentPane().add(home_button_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        schoolresult_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/school result 02.png"))); // NOI18N
        getContentPane().add(schoolresult_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        registation_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/registation button 04.png"))); // NOI18N
        getContentPane().add(registation_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, -1, -1));

        admission_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/admission 02.png"))); // NOI18N
        getContentPane().add(admission_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, -1, -1));

        routine_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Routine 04.png"))); // NOI18N
        routine_02.setToolTipText("");
        getContentPane().add(routine_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 430, -1, -1));

        logout_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Log Out button 06.png"))); // NOI18N
        getContentPane().add(logout_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void home_button_01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_button_01MouseEntered
        home_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Home button 06.png")));
    }//GEN-LAST:event_home_button_01MouseEntered

    private void home_button_01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_home_button_01MouseExited
        home_button_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Home button 05.png")));
    }//GEN-LAST:event_home_button_01MouseExited

    private void schoolresult_01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schoolresult_01MouseEntered
        schoolresult_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/school result 02.png")));
    }//GEN-LAST:event_schoolresult_01MouseEntered

    private void schoolresult_01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_schoolresult_01MouseExited
        schoolresult_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/school result 01.png")));
    }//GEN-LAST:event_schoolresult_01MouseExited

    private void registation_01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registation_01MouseEntered
        registation_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/registation button 04.png")));
    }//GEN-LAST:event_registation_01MouseEntered

    private void registation_01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registation_01MouseExited
        registation_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/registation button 03.png")));
    }//GEN-LAST:event_registation_01MouseExited

    private void admission_01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admission_01MouseEntered
        admission_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/admission 02.png")));
    }//GEN-LAST:event_admission_01MouseEntered

    private void admission_01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_admission_01MouseExited
       admission_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/admission 01.png")));
    }//GEN-LAST:event_admission_01MouseExited

    private void routine_01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_routine_01MouseEntered
        routine_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Routine 04.png")));
    }//GEN-LAST:event_routine_01MouseEntered

    private void routine_01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_routine_01MouseExited
        routine_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Routine 03.png")));
    }//GEN-LAST:event_routine_01MouseExited

    private void logout_01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_01MouseEntered
        logout_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Log Out button 06.png")));
    }//GEN-LAST:event_logout_01MouseEntered

    private void logout_01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_01MouseExited
        logout_01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/Log Out button 05.png")));
    }//GEN-LAST:event_logout_01MouseExited

    private void logout_01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logout_01MouseClicked
        new teacher_login().setVisible(true);
        dispose();
    }//GEN-LAST:event_logout_01MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(teacher_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(teacher_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(teacher_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(teacher_home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new teacher_home().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel admission_01;
    private javax.swing.JLabel admission_02;
    private javax.swing.JLabel bg;
    private javax.swing.JLabel home_button_01;
    private javax.swing.JLabel home_button_02;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel logout_01;
    private javax.swing.JLabel logout_02;
    private javax.swing.JLabel registation_01;
    private javax.swing.JLabel registation_02;
    private javax.swing.JLabel routine_01;
    private javax.swing.JLabel routine_02;
    private javax.swing.JLabel schoolresult_01;
    private javax.swing.JLabel schoolresult_02;
    // End of variables declaration//GEN-END:variables
}
