/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Log_IN;
import home.govt_home;
import java.awt.HeadlessException;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author AL-SABA
 */
public class govt_login extends javax.swing.JFrame {

    /**
     * Creates new form govt_login
     */
    public govt_login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        id01 = new javax.swing.JTextField();
        pass01 = new javax.swing.JPasswordField();
        log_in01 = new javax.swing.JButton();
        icon01 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        login_button_02 = new javax.swing.JLabel();
        icon02 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jLabel2.setText("Admin ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, -1, -1));

        jLabel3.setText("Password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 320, -1, -1));

        id01.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        id01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(id01, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 270, 140, 30));

        pass01.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        pass01.setActionCommand("<Not Set>");
        pass01.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.add(pass01, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 350, 140, 30));

        log_in01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/login button 09.png"))); // NOI18N
        log_in01.setContentAreaFilled(false);
        log_in01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                log_in01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                log_in01MouseExited(evt);
            }
        });
        log_in01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                log_in01ActionPerformed(evt);
            }
        });
        jPanel1.add(log_in01, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 400, -1, -1));

        icon01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon04.png"))); // NOI18N
        icon01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon01MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                icon01MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                icon01MouseExited(evt);
            }
        });
        jPanel1.add(icon01, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Background/gov_bg.jpg"))); // NOI18N
        jPanel1.add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 791));

        login_button_02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/login button 08.png"))); // NOI18N
        jPanel1.add(login_button_02, new org.netbeans.lib.awtextra.AbsoluteConstraints(782, 393, 80, 30));

        icon02.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon01.png"))); // NOI18N
        jPanel1.add(icon02, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 360, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void icon01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon01MouseEntered
      icon01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon01.png")));
    }//GEN-LAST:event_icon01MouseEntered

    private void icon01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon01MouseExited
          icon01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icon04.png")));
    }//GEN-LAST:event_icon01MouseExited

    private void icon01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon01MouseClicked
        new Home_page_all_account().setVisible(true);
        dispose();
    }//GEN-LAST:event_icon01MouseClicked

    private void log_in01MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_in01MouseEntered
       log_in01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/login button 08.png")));
    }//GEN-LAST:event_log_in01MouseEntered

    private void log_in01MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_log_in01MouseExited
        log_in01.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Button/login button 09.png")));
    }//GEN-LAST:event_log_in01MouseExited

    private void log_in01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_log_in01ActionPerformed
       var id=id01.getText();
       var pass=pass01.getText();
       
       try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://127.0.0.1:3307/nsid","root","");
        Statement stmt=con.createStatement();
        ResultSet rs=stmt.executeQuery("SELECT * FROM admin where email ='"+id+"' and password='"+pass+"'");
        if(rs.next()){
            java.awt.EventQueue.invokeLater(() -> {
            new govt_home().setVisible(true);
            dispose();
        });

        } 
        else{
             JOptionPane.showMessageDialog(null,"Incorrect Enter your ID & Password");  
        }
       }
       catch(HeadlessException | ClassNotFoundException | SQLException e){
           System.out.print(e);
       } 
       
    }//GEN-LAST:event_log_in01ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(govt_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(govt_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(govt_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(govt_login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new govt_login().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JLabel icon01;
    private javax.swing.JLabel icon02;
    private javax.swing.JTextField id01;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton log_in01;
    private javax.swing.JLabel login_button_02;
    private javax.swing.JPasswordField pass01;
    // End of variables declaration//GEN-END:variables
}
